### ISSUE TITLE
location URI is not precise enough.

### ISSUE THREAD

**Issue by workergnome** [american-art/SAAM#10]
Take, for example, http://data.americanartcollaborative.org/page/saam/constituent/id/1059.

It appears that poor Woodrow was born in Lexington, Virginia; Lexington, Massachusetts; Lexington, Kentucky; and Lexington, Oklahoma.  This seems _unlikely_.  

Please use a more precise URI for locations.

**Comment by workergnome** [comment]
Noted in Institutional review:

> Birthplace or deathplace connected to multiple cities.  EX:  Allan Rohan Crite born in Plainfield, NJ – also list Plainfield NH & Plainfield CT (not coming from SAAM data)

**Comment by bsnikhila** [comment]
Fixed.
