### ISSUE TITLE
Link each object to the museum

### ISSUE THREAD

**Issue by workergnome** [american-art/SAAM#16]
There are a bunch of books in the triple store—http://data.americanartcollaborative.org/page/saam/book/id/108, for example.  They have no data, and I have no way to distinguish between books and works of art.  

Open for suggestions.

**Comment by workergnome** [comment]
I suggest, to solve this, that we add:

```ttl
_:work_of_art crm:P46i_forms_part_of <http://data.americanartcollaborative.org/saam/collection>;
<http://data.americanartcollaborative.org/saam/collection> a crm:E78_Collection; 
    rdfs:label "The collection of the Smithsonian American Art Museum";
    P52_has_current_owner <http://data.americanartcollaborative.org/saam>.
```

To every art object in this and every other institution (with the appropriate values, of course).

**Comment by VladimirAlexiev** [comment]
That is quite correct, and I'm not sure why you and @azaroth42 had qualms of calling a museum collection `E78_Collection`.
Same as the above mapping should be used for department. We have two options

Either to say the object belongs to a departmental collection, which itself is part of the museum collection:
```ttl
<work> crm:P46i_forms_part_of <saam/fine-arts/collection>.

<saam/fine-arts/collection> a crm:E78_Collection;
  crm:P46i_forms_part_of <saam/collection>;
  rdfs:label "Fine Arts collection of the Smithsonian American Art Museum";
  crm:P49_has_former_or_current_keeper <saam/fine-arts>;
  crm:P109_has_current_or_former_curator <saam/fine-arts>.

<saam/collection> a crm:E78_Collection; 
  rdfs:label "Collection of the Smithsonian American Art Museum";
  crm:P49_has_former_or_current_keeper <saam>;
  crm:P109_has_current_or_former_curator <saam>.
```

Or to say the object belongs to two collections (Museum and Department), and the rest of the data is the same.
```ttl
<work> crm:P46i_forms_part_of <saam/fine-arts/collection>, <saam/collection>.
```
I think I prefer this for uniformity: @workergnome needs it to find all works of a museum,
and we don't want the `<saam/collection>` triple to depend on the lack of Department info.

We should also state all possible info about the department and museum (relates to https://github.com/american-art/wam/issues/15):
```ttl
<saam/fine-arts> a crm:E74_Group;
  crm:P2_has_type aat:300263534; # department (organizational unit)
  rdfs:label "Fine Arts department of the Smithsonian American Art Museum";
  crm:P107i_is_current_or_former_member_of <saam>.

<saam> a crm:E40_Legal_Body;
  crm:P2_has_type aat:300312281; # museum (institution)
  rdfs:label "Smithsonian American Art Museum";
  owl:sameAs ulan:500311465-agent.
```

In the case of SAAM, we can even state it's part of a bigger institution:
```ttl
<saam> crm:P107i_is_current_or_former_member_of <smithsonian>.

<smithsonian> a crm:E40_Legal_Body;
  rdfs:label "Smithsonian Institution";
  crm:P2_has_type aat:300312281; # museum (institution)
  owl:sameAs ulan:500237333-agent.
```
Please comment

**Comment by workergnome** [comment]
No qualms at all about calling museum collections `E78_Collection`.  Departmentatl collections are messier—I'd need to talk to museum people to see if it is semantically accurate.  (do departments have collecting plans, or is that something else?  The E78 scope note is maddeningly precise.)

I'm still cranky about the `owl:sameAs` vs `skos:exactMatch`, but that's because I anticipate this data set being merged with other, yet-to-be-determined external resources, and I assume someone will smush them.  

Everything else here I agree with, and if we can get it, it would be lovely.

**Comment by azaroth42** [comment]
I prefer `Work partOf FineArts . FineArts partOf Museum .` rather than everything being part of all levels of the hierarchy directly.

I agree with `skos:exactMatch`. The contributors to ULAN's -agent, are not the contributors to SAAM's agent.

**Comment by VladimirAlexiev** [comment]
`ulan:nnn-agent` doesn't have contributors. `ulan:nnn` is a skos:Concept with contributors, pointing to `ulan:nnn-agent`

**Comment by sosarasays** [comment]
I am highlighting this issue as high-priority/"deal breaker" @workergnome @VladimirAlexiev as it relates to the Browse app. In the 200 record sample set (what is visible in the browse app/validator tool), we currently only see books, no accessioned artworks.

**Comment by sosarasays** [comment]
OK, I think we have resolved the question about books, specifically, but the larger problem is that SAAM isn't flagged as "owner" or collecting institution for our objects, as @workergnome highlighted. Not sure if this is already flagged in another ticket...

**Comment by workergnome** [comment]
It was not, but I've created one that is specific about the needs: https://github.com/american-art/SAAM/issues/37.

**Comment by caknoblock** [comment]
Agreed, this problem still needs to be fixed.  There is a model for owner, but I think it is wrong.  It needs to be done in the same way that GM is done as in this model: 
https://github.com/american-art/GM/blob/master/Objects/Objects-model.pdf <https://github.com/american-art/GM/blob/master/Objects/Objects-model.pdf>

**Comment by bsnikhila** [comment]
The owner data has been fixed.
