### ISSUE TITLE
SAAM object 0 and PUAM constituent 6388 are deficient

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/SAAM#18]
http://data.americanartcollaborative.org/page/saam/object/id/0
Just dimensions?!?

**Comment by workergnome** [comment]
This feels to me like there are some triples left over in the database from previous mappings that haven't been purged.  @bsnikhila, can you verify that you're purging old triples when you reload?

**Comment by VladimirAlexiev** [comment]
Looks like it, and here's another zombie: http://data.americanartcollaborative.org/puam/constituent/6388

**Comment by bsnikhila** [comment]
PUAM: There is a record with Constituent ID 6388 in the apicongeography file, but no record with that ID in the apiconstituents file. This is why it is appearing as a zombie.

Similarly for saam, only the dimensions file has a record with object ID 0.

**Comment by bsnikhila** [comment]
It seems like these zombie records have not yet been removed.

**Comment by VladimirAlexiev** [comment]
http://data.americanartcollaborative.org/saam/object/id/0 is gone, which is a relief.
http://data.americanartcollaborative.org/saam/object/id/1998_84_8 is an example object.
