### ISSUE TITLE
SAAM dimensions are mixed up

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/SAAM#19]
http://data.americanartcollaborative.org/page/saam/object/id/0/overall_1/dimension
http://data.americanartcollaborative.org/page/saam/object/id/1/sheet/dimension

All props (type, unit, value) of 2-3 dimensions are mixed up together.
You need separate URLs, eg
http://data.americanartcollaborative.org/page/saam/object/id/1/sheet/dimension/height/IN
http://data.americanartcollaborative.org/page/saam/object/id/1/sheet/dimension/height/CM
http://data.americanartcollaborative.org/page/saam/object/id/1/sheet/dimension/width/IN
http://data.americanartcollaborative.org/page/saam/object/id/1/sheet/dimension/width/CM

**Comment by bsnikhila** [comment]
Same as #20
