### ISSUE TITLE
Two different data sources for artist firstname/lastname

### ISSUE THREAD

**Issue by mit2nil** [american-art/SAAM#2]
Hi,

WebMakers_view.csv contains fields 'LastName' and 'FirstName' which are also present in 'WebConAltNames.csv'. Moreover, there are cases when the values are inconsistent.

e.g. "Ansel Easton" is FirstName for object id 20 in WebConAltNames.csv but it is "Ansel" in "WebMakers_view.csv"

**Comment by workergnome** [comment]
I would assume that the AltNames.csv contains alternate names, and should be mapped as such.

**Comment by rkbrasse** [comment]
Ansel Easton is an alternate name for Ansel.  The WebConAltNames.csv contains a list of Constituents alternate names which is why the first and last names columns may not 100% align.

**Comment by mit2nil** [comment]
OK. In the reference model, we just have one label for alternate name. Is it fine to join prefix+first name+last name+suffix to get single label per data sample?

**Comment by rkbrasse** [comment]
Do you have any concerns about n artist having more than one alternate name?

**Comment by mit2nil** [comment]
Do you mean different alternate name per field? First name as different alternate name and last name as different alternate name?

**Comment by rkbrasse** [comment]
Pardon it is fine to have a prefix + firstname lastname + suffix would be one alternate name.

**Comment by mit2nil** [comment]
Thanks for clarification.

**Comment by mit2nil** [comment]
One more similar issue. Even WebConstituents_person_view.csv file is containing first name, last name fields. Between this file and web makers which names should be taken?

**Comment by workergnome** [comment]
I would suggest modeling all alternate names the same way that you model primary names, other than the 'primary field' type on the core name.  The parts of the name are linked to the main appellation per-name form.

So "Beth Smith" has a first name "Beth" and a last name "Smith", and Beth Smith has a secondary name "Elizabeth Smith" that has a first name "Elizabeth" and a last name "Smith"., and those parts are linked to their main appalation using the `p106_is_composed_of`.

@rkbrasse can tell you which name is the "primary" one, but the model for names should be consistent.  That way I can query for "all first names of the entity "Elizabeth Smith" and get both Beth and Elizabeth, but if I have to choose a display name I know that "Beth Smith" is the preferred name.

**Comment by rkbrasse** [comment]
I believe person_view and institution_view are derived from the same tables as web_makers. So the names should be the same.  I'll check here to see which should take precedence.

**Comment by mit2nil** [comment]
Any update on primary name field @rkbrasse ?

**Comment by rkbrasse** [comment]
I've been told that WebConstituents should be used for the primary name.
