### ISSUE TITLE
SAAM dimension units should be URLs

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/SAAM#20]
http://data.americanartcollaborative.org/page/saam/object/id/0/overall_1/dimension
http://data.americanartcollaborative.org/page/saam/object/id/1/sheet/dimension

Uses literals "IN", "CM" for the units. It may not be obvious [from the mapping](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_19-search_0) but units must be URLs (E55_Type). 
The best is to use AAT URLs: aat:300379098 (cm), aat:300379100 (inch): @workergnome pls confirm

**Comment by workergnome** [comment]
I agree.  They should be types, they should come from a vocabulary, and the type should have a label.

**Comment by bsnikhila** [comment]
I think these were extra objects that were not supposed to be in the files and have now been removed.
