### ISSUE TITLE
SAAM constituent alt names

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/SAAM#22]
http://data.americanartcollaborative.org/page/saam/constituent/id/2/alt_name is a bad choice of URL since some have several alt names: then the data gets mixed up.

WebConAltNames doesn't have alt name IDs, so you need to use the alt name **type** in the URL. Eg split the above to two URLs:
http://data.americanartcollaborative.org/page/saam/constituent/id/2/birthormaidenname
http://data.americanartcollaborative.org/page/saam/constituent/id/2/variantname

**Comment by bsnikhila** [comment]
Fixed.
