### ISSUE TITLE
Sort date substituted for death date.  

### ISSUE THREAD

**Issue by workergnome** [american-art/SAAM#32]
From institutional review:

> Sort date substituted for death date.  EX:  Eileen Cowin died in 2047

See http://data.americanartcollaborative.org/page/saam/constituent/id/1028 for an example.

**Comment by bsnikhila** [comment]
2047 is provided as the EndDate for constituent 1028 in the datafile WebConstituents_person_view.

**Comment by VladimirAlexiev** [comment]
Right.
There are also SAAM/WebConDatesDeath/WebConDates.csv and SAAM/WebConDatesBirth/WebConDates.csv (being the same file!) that have different info:
```
ConDateID,ConstituentID,DateDescription,DateBegSearch,DateEndSearch,Remarks,LoginID,EnteredDate,SysTimeStamp,DayBegSearch,DayEndSearch,MonthBegSearch,MonthEndSearch
3438,1028,Birth Date,1947,0,,sa/Todd,1998-07-06 19:59:00.67,0000000100045E38,17,,8,
3439,1028,Record entered in Inquire,1990,0,,sa/Todd,1998-07-06 19:59:00.7,0000000100045E3B,1,,10,
3440,1028,Record last changed in Inquire,1997,0,,sa/Todd,1998-07-06 19:59:00.717,0000000100045E3E,20,,6,
(no death date)
```
@rkbrasse or someone else from SAAM, can you explain which is the correct source file to use?

**Comment by rkbrasse** [comment]
I just looked at the situation here. The files you are mentioning look like they were derived by bsnikhila from the original WebConDates.csv file.  The example death date given does not even exist in the original file.  I'm not sure where that date came from.

**Comment by caknoblock** [comment]
@rkbrasse This death date is coming from the file: WebConstituents_person_view.  I just checked it 2047 is the enddate given for constituent #1028 in that file.  Looks like the model is fine and it is a problem in the raw data.

**Comment by rkbrasse** [comment]
OK Eggs on my face, I was looking at some csv from February where these beg and end dates were not present.  That data is most certainly there in the original WebConstituents_person_view.csv and in the DB from which these CSV's are created.  I'll check with someone more acquainted with the data's origin and see what the logic, if any, is behind the 2047 date.  WebConDates seems to be the more vetted data from my perspective.  Will update once I hear from my data person on this.

**Comment by rkbrasse** [comment]
The odd dates are range dates when the artist doesn’t have complete life dates (one hundred years from date of birth forward, or one hundred years from date of death backward).  On the Webconstituents table BeginDate and EndDate  are used for internal TMS searching and not for  websites.
 
The  WebCondates  --Website should only use these types: Birth Date, Death Date
 
Another note On the WebConsitutents_person_view table, we use three codes (Provisional, Candidate, Verified) in the column "Code"  to identify constituents who are creators of artworks in the permanent collection.  All of the other constituents without codes are not used, they are donors, staff,  etc.

**Comment by bsnikhila** [comment]
I have now used the WebConDates files.
