### ISSUE TITLE
Birth/Death labels include locations

### ISSUE THREAD

**Issue by workergnome** [american-art/SAAM#33]
From institutional review:

> Broken cities when hyphenated.  EX:  Walter Crump born in Winston-Salem, NC – listed as born Winston, died Salem.

The parsing code for birth/death dates breaks on hyphenated location names.  These labels should not include locations at all—they're labelling the time, not the death.
For http://data.americanartcollaborative.org/page/saam/constituent/id/1060, see 
http://data.americanartcollaborative.org/page/saam/constituent/id/1060/birth/time

**Comment by bsnikhila** [comment]
This looks fixed.
