### ISSUE TITLE
SAMM constituent nationality URLs

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/SAAM#36]
Don't use per-object constituent nationality URLs like http://data.americanartcollaborative.org/saam/constituent/id/1008/nationality.
Use per-museum URLs like http://data.americanartcollaborative.org/saam/nationality/French

**Comment by bsnikhila** [comment]
Fixed.
http://data.americanartcollaborative.org/page/saam/thesauri/nationality/american
