### ISSUE TITLE
ObjectID missing

### ISSUE THREAD

**Issue by bsnikhila** [american-art/SAAM#5]
The ObjectID column seems to be missing in the WebObjDescription [file](https://github.com/american-art/SAAM/tree/master/Objects)

**Comment by rkbrasse** [comment]
objectnumber may be a better choice for associating objects.  ObjectID is a storage system specific ID which may or maynot be present in a table.  Basically I guess the rule of thumb should be ObjectId can be used where present and ObjectNumber when you are unable to find an ObjectId.

**Comment by bsnikhila** [comment]
I noticed that there are multiple objects with the same Object Number.
For example in the file WebObjCaption, the 3records with Object IDs 34934, 21823 and 21469, all have the same Object No 1985.1.
When I look at the web pages for these records, I see that the Object Numbers are actually 1985.1, 1985.10 and 1985.100 respectively. So there probably is an issue in the way the CSV files are generated. 
If this is rectified, I can use the Object Number to generate the URIs for the objects as the value I use to generate the URIs should be unique.

**Comment by workergnome** [comment]
@rkbrasse — This looks like something that you'd have to do on your end.

**Comment by rkbrasse** [comment]
Yes this is a me thing.  I'l let ya know when I get it figure out.

Rich Brassell
Web Developer at the Smithsonian American Art Museum
<http://americanart.si.edu/>
Work ph# 202-633-8579
Cell   ph# 240-338-1923

**Comment by bsnikhila** [comment]
Has this been updated?

**Comment by rkbrasse** [comment]
Yes the open pull request is set up for this.

**Comment by caknoblock** [comment]
I just merged this pull request.
