### ISSUE TITLE
Missing fields:

### ISSUE THREAD

**Issue by workergnome** [american-art/SAAM#51]
-Title
-Date
-Medium
-Classification
-Subjects
-Credit line
-Accession number

**Comment by rkbrasse** [comment]
Where are they missing from?

**Comment by workergnome** [comment]
This was copied and pasted from the email y'all sent after reviewing your data.  I don't have a lot of context for it, unfortunately—that's all it said.

**Comment by bsnikhila** [comment]
There was an issue with uploading the data to the triple store. The triples have been uploaded now, and these fields should no longer be missing.
