### ISSUE TITLE
Many blank nodes

### ISSUE THREAD

**Issue by workergnome** [american-art/SAAM#7]
If you look at http://data.americanartcollaborative.org/page/saam/object/id/77726, you'll see at least a couple anonymous nodes.  I'm also getting blank nodes when I query for actors, and it appears that they're coming from the SAAM mapping.

```
SELECT * WHERE { 
  
      {?s a <http://www.cidoc-crm.org/cidoc-crm/E39_Actor>} UNION
      {?s a <http://www.cidoc-crm.org/cidoc-crm/E21_Person>} UNION
      {?s a <http://www.cidoc-crm.org/cidoc-crm/E74_Group>} UNION
      {?s a <http://www.cidoc-crm.org/cidoc-crm/E40_Legal_Body>}
  	  
      FILTER NOT EXISTS {?s <http://www.cidoc-crm.org/cidoc-crm/P2_has_type> <http://vocab.getty.edu/aat/300379842>}
      FILTER NOT EXISTS {?s <http://www.cidoc-crm.org/cidoc-crm/P2_has_type> <http://vocab.getty.edu/aat/300263534>}
      FILTER isBlank(?s)
    }
```

returns blank nodes, and there should never be a Actor without an ID.

**Comment by bsnikhila** [comment]
Seems to be fixed. 
Note: http://data.americanartcollaborative.org/page/saam/object/id/77726 changed to http://data.americanartcollaborative.org/page/saam/object/id/RF_3_151
